function get_quality_check(script_nr,subjects, rec_length, events, cfg)
% the function creates plots for the number of events found for each subject and the
% recording length. It saves these plots to a separate folder coded at cfg.dir.qualitycheck
if isequal(script_nr,1)

    fileID = fopen([cfg.dir.qualitycheck, 'project_report.txt'],'a+');
    fprintf(fileID,'\n %s',datestr(datetime),'report from script01_import ', ['Data directory: ',cfg.dir.main],...
        ['Processed subjects: ', strjoin(subjects, ', ')], ['New reference (yes/no): ', num2str(cfg.prep.do_rereference)],...
        ['Reference channel: ', cfg.prep.reref_chan]);
    fclose(fileID);
    
    %plot and save figure for the recording length
    fig_length = bar(rec_length), xlabel('Participants', 'FontSize', 14), ylabel('Length of recordings (min)', 'FontSize', 14)
    saveas(fig_length, [cfg.dir.qualitycheck, 'recording length.png'])

    %plot and save figure for the number of event types. Subjects are color coded
    fig_events = figure, bar(events(:,1),events(:,2:end)), xlabel('Events', 'FontSize', 12), ylabel('Number of occurances', 'FontSize', 12),...
        legend(string(1:length(subjects)), 'Location','southoutside', 'Orientation','horizontal','NumColumns',6, 'FontSize',5)
    saveas(fig_events, [cfg.dir.qualitycheck,'events per participant.png'])

elseif isequal(script_nr,2)

    text = sprintf(['\n%s\n report from script02_simple_prep\n' ...
        'Data directory: %s\n' ...
        'Processed subjects: %s\n' ...
        'These channels are not filtered: %s\n' ...
        'High pass filter (yes/no): %s\n' ...
        'High pass filter type: %s\n' ...
        'High pass filter limit: %s\n' ...
        'Low pass filter (yes/no): %s\n' ...
        'Low pass filter limit: %s\n' ...
        'Low pass filter bandwidth: %s\n' ...
        'Notch filter (yes/no): %s\n' ...
        'Downsample(yes/no): %s\n'], ...
        datestr(datetime), ...
        cfg.dir.main, ...
        strjoin(subjects, ', '), ...
        num2str(events), ...
        num2str(cfg.prep.do_hp_filter), ...
        cfg.prep.hp_filter_type, ...
        num2str(cfg.prep.hp_filter_limit), ...
        num2str(cfg.prep.do_lp_filter), ...
        num2str(cfg.prep.lp_filter_limit), ...
        num2str(cfg.prep.lp_filter_tbandwidth), ...
        num2str(cfg.prep.do_notch_filter), ...
        num2str(cfg.prep.do_resampling));

    fileID = fopen([cfg.dir.qualitycheck, 'project_report.txt'],'a+');
    fprintf(fileID,'%s',text);
    fclose(fileID);

    if cfg.prep.do_resampling == 1
        text2 = sprintf('Downsampled to: %s\n', ...
            num2str(cfg.prep.new_sampling_rate));
        fileID = fopen([cfg.dir.qualitycheck, 'project_report.txt'],'a+');
        fprintf(fileID,'%s',text2);
        fclose(fileID);
    end

    clear text text2
elseif isequal(script_nr,3)
    msg = sprintf(['\n%s\nreport from script03_artifact_rejection\n' ...
        'Data directory: %s\n' ...
        'Processed subjects: %s\n' ...
        'Flat channels: %s\n' ...
        'Number of flat channels: %d\n' ...
        'Duration before artifact rejection (minutes): %.4f\n' ...
        'Duration after artifact rejection (minutes): %.4f\n' ...
        'Keeping %.1f%% of the data.\n'], ...
        datestr(datetime), ...
        cfg.dir.main, ...
        strjoin(subjects, ', '), ...
        num2str(events), ...
        length(events), ...
        rec_length.before, ...
        rec_length.after, ...
        rec_length.after/rec_length.before*100);

    fileID = fopen([cfg.dir.qualitycheck, 'project_report.txt'], 'a+');
    fprintf(fileID, '%s', msg);
    fclose(fileID);
elseif isequal(script_nr,4)
    msg = sprintf(['\n%s\nreport from script04_ica\n' ...
        'Data directory: %s\n' ...
        'Processed subjects: %s\n' ...
        'High pass filter (yes/no): %d\n' ...
        'High pass filter cutoff: %d\n' ...
        'Baseline removal (yes/no): %d\n'], ...
        datestr(datetime), ...
        cfg.dir.main, ...
        strjoin(subjects, ', '), ...
        cfg.ica.do_ICA_hp_filter, ...
        cfg.ica.hp_ICA_filter_limit, ...
        cfg.ica.do_baseline_removal);

    fileID = fopen([cfg.dir.qualitycheck, 'project_report.txt'],'a+');
    fprintf(fileID,'%s',msg);
    fclose(fileID);
elseif isequal(script_nr,5)

    msg = sprintf(['\n%s\nreport from script05_icareject\n' ...
        'Data directory: %s\n' ...
        'Processed subjects: %s\n' ...
        'Number of components rejected: %s\n'], ...
        datestr(datetime), ...
        cfg.dir.main, ...
        strjoin(subjects, ', '), ...
        num2str(events));

    fileID = fopen([cfg.dir.qualitycheck, 'project_report.txt'],'a+');
    fprintf(fileID,'%s',msg);
    fclose(fileID);
end